version: '3.3'
services:
  app:
    build:
      context: ./CalculatorProblemV2
      dockerfile: Dockerfile
      # tty: true
    volumes:
      - ../..:/workspaces:cached
    ports:
      - 8092:8092

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=calculator_problem_v2
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      # - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  react-app:
    build:
      context: ./CalculatorProblem_FE
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  db_data:
